PROBLEM 01: ARRAY CREATION

In [2]:
import numpy as np

#Initializing an empty array of size 2x2
empty_array = np.empty((2, 2))
print("Empty Array:")
print(empty_array)

#Initializing an all-ones array of size 4x2
ones_array = np.ones((4, 2))
print("\nAll Ones Array:")
print(ones_array)

# Returning a new array of shape 3x3 filled with the value 7
full_array = np.full((3, 3), 7)
print("\nFull Array (filled with 7):")
print(full_array)

# Returning a new array of zeros with the same shape as an existing array
existing_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(existing_array)
print("\nZeros Like Array:")
print(zeros_like_array)

#Returning a new array o with the same shape as an existing array
ones_like_array = np.ones_like(existing_array)
print("\nOnes Like Array:")
print(ones_like_array)

#Converting an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array_from_list = np.array(new_list)
print("\nNumPy Array from List:")
print(numpy_array_from_list)


Empty Array:
[[5.03194577e-310 0.00000000e+000]
 [6.58454617e-310 6.58452508e-310]]

All Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full Array (filled with 7):
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Array:
[[0 0]
 [0 0]]

Ones Like Array:
[[1 1]
 [1 1]]

NumPy Array from List:
[1 2 3 4]


Problem 02: ARRAY MANIPULATION NUMERICAL RANGES AND ARRAY INDEXING

In [4]:
import numpy as np

#Creating an array with numbers from 10 to 49
array_range = np.arange(10, 50)
print("Array from 10 to 49:")
print(array_range)

#Creating a 3x3 table with numbers from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Table with Numbers 0 to 8:")
print(matrix_3x3)

#Creating a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:")
print(identity_matrix)

#Creating 30 random numbers and find the average
random_array = np.random.random(30)
print("\nAverage of 30 Random Numbers:")
print(random_array.mean())

#Creating a 10x10 table of random numbers and finding the smallest and largest
random_10x10 = np.random.random((10, 10))
print("\nSmallest and Largest Numbers in a 10x10 Random Table:")
print("Smallest:", random_10x10.min())
print("Largest:", random_10x10.max())

#Creating a list of 10 zeros and change the 5th number to 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nList of 10 Zeros with 5th Element as 1:")
print(zero_array)

#Reversing a list
arr = np.array([1, 2, 0, 0, 4, 0])
print("\nReversed List:")
print(arr[::-1])

#Creating a 2D table with 1s on the edges and 0s inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\nTable with 1s on Edges and 0s Inside:")
print(border_array)

#Creating an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:")
print(checkerboard)


Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Table with Numbers 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Average of 30 Random Numbers:
0.5051157332263222

Smallest and Largest Numbers in a 10x10 Random Table:
Smallest: 0.0004423655760803502
Largest: 0.9954662145694748

List of 10 Zeros with 5th Element as 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed List:
[0 4 0 0 2 1]

Table with 1s on Edges and 0s Inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 Checkerboard Pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


PROBLEM 03:ARRAY OPERATION

In [9]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_result = x + y
print("1. Addition of x and y:")
print(add_result)

subtract_result = x - y
print("\n2. Subtraction of x and y:")
print(subtract_result)

multiply_result = x * 2
print("\n3. Multiplication of x with 2:")
print(multiply_result)

square_result = x ** 2
print("\n4. Square of each element in x:")
print(square_result)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n5. Dot products:")
print(f"Dot product of v and w: {dot_vw}")
print("Dot product of x and v:")
print(dot_xv)
print("Dot product of x and y:")
print(dot_xy)

concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))
print("\n6. Concatenation:")
print("Concatenation of x and y along rows:")
print(concat_xy)
print("Concatenation of v and w along columns:")
print(concat_vw)

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\n7. Concatenation of x and v:")
    print(concat_xv)
except ValueError as e:
    print("\n7. Error in concatenating x and v:")
    print(e)
    print("Explanation: This error occurs because the dimensions of x (2x2) and v (1x2) don't match along axis 1.")


1. Addition of x and y:
[[ 6  8]
 [10 13]]

2. Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

3. Multiplication of x with 2:
[[ 2  4]
 [ 6 10]]

4. Square of each element in x:
[[ 1  4]
 [ 9 25]]

5. Dot products:
Dot product of v and w: 219
Dot product of x and v:
[29 77]
Dot product of x and y:
[[19 22]
 [50 58]]

6. Concatenation:
Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
[[ 9 10]
 [11 12]]

7. Error in concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: This error occurs because the dimensions of x (2x2) and v (1x2) don't match along axis 1.


PROBLEM 04: MATRIX OPERATIONS


In [6]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("1. A * A^(-1) = Identity matrix:")
print(identity)


AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB and BA matrices:")
print("AB =")
print(AB)
print("BA =")
print(BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))


AB_transpose = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\n3. (AB)^T and B^T * A^T:")
print("(AB)^T =")
print(AB_transpose)
print("B^T * A^T =")
print(BT_AT)
print("Is (AB)^T equal to B^T * A^T?", np.array_equal(AB_transpose, BT_AT))


1. A * A^(-1) = Identity matrix:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB and BA matrices:
AB =
[[23 13]
 [51 29]]
BA =
[[36 44]
 [13 16]]
Are AB and BA equal? False

3. (AB)^T and B^T * A^T:
(AB)^T =
[[23 51]
 [13 29]]
B^T * A^T =
[[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A^T? True


In [7]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution for the system of equations:")
print(f"x = {X[0]:.2f}, y = {X[1]:.2f}, z = {X[2]:.2f}")


Solution for the system of equations:
x = 2.00, y = 1.00, z = -2.00


4.2 EXPERIMENTS


In [8]:
import numpy as np
import time

# 1. Element-wise Addition
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
array1 = np.arange(size)
array2 = np.arange(size)

start = time.time()
result_list_add = [x + y for x, y in zip(list1, list2)]
end = time.time()
print(f"Time taken for addition with Python lists: {end - start:.5f} seconds")

start = time.time()
result_array_add = array1 + array2
end = time.time()
print(f"Time taken for addition with NumPy arrays: {end - start:.5f} seconds")

# 2. Element-wise Multiplication
start = time.time()
result_list_mul = [x * y for x, y in zip(list1, list2)]
end = time.time()
print(f"Time taken for multiplication with Python lists: {end - start:.5f} seconds")


start = time.time()
result_array_mul = array1 * array2
end = time.time()
print(f"Time taken for multiplication with NumPy arrays: {end - start:.5f} seconds")

# 3. Dot Product
start = time.time()
dot_product_list = sum(x * y for x, y in zip(list1, list2))
end = time.time()
print(f"Time taken for dot product with Python lists: {end - start:.5f} seconds")

start = time.time()
dot_product_array = np.dot(array1, array2)
end = time.time()
print(f"Time taken for dot product with NumPy arrays: {end - start:.5f} seconds")

# 4. Matrix Multiplication
matrix_size = 1000
list_matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
list_matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
np_matrix1 = np.array(list_matrix1)
np_matrix2 = np.array(list_matrix2)

start = time.time()
result_matrix_list = [[sum(a * b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
end = time.time()
print(f"Time taken for matrix multiplication with Python lists: {end - start:.5f} seconds")


start = time.time()
result_matrix_np = np.dot(np_matrix1, np_matrix2)
end = time.time()
print(f"Time taken for matrix multiplication with NumPy arrays: {end - start:.5f} seconds")


Time taken for addition with Python lists: 0.09673 seconds
Time taken for addition with NumPy arrays: 0.00521 seconds
Time taken for multiplication with Python lists: 0.10558 seconds
Time taken for multiplication with NumPy arrays: 0.00509 seconds
Time taken for dot product with Python lists: 0.11003 seconds
Time taken for dot product with NumPy arrays: 0.00202 seconds
Time taken for matrix multiplication with Python lists: 198.00929 seconds
Time taken for matrix multiplication with NumPy arrays: 1.58519 seconds
